etunimi = input("Etunimi: ")
sukunimi = input("Sukunimi: ")
osoite = input("Katuosoite: ")
pnrokaupunki = input("Postinumero ja kaupunki: ")
print(etunimi + " " + sukunimi)
print(osoite)
print(pnrokaupunki)